denoland/deno_doc

src/parser.rs
Ref https://github.com/denoland/deno/issues/7361
=> fix: DocError stack overflow when displaying

.gitattributes, Cargo.lock, Cargo.toml, README.md, examples/ddoc/main.rs
=> add example

src/parser.rs, src/tests.rs
=> fix: export interface and class with same name

Cargo.lock, Cargo.toml
Also not pinning patch version anymore.
=> upgrade: swc_ecmascript, swc_common

Cargo.lock, Cargo.toml
=> upgrade: swc_ecmascript 0.15.1

src/module.rs, src/namespace.rs, src/node.rs, src/parser.rs
* This PR re-lands denoland/deno#7083 (that is probably lost when moving the repository).
* All code contained in this PR was originally written by @bartlomieju.
=> refactor(doc): add helper functions for DocNode

src/parser.rs, src/tests.rs
=> feat: allow deep reexports

.rustfmt.toml, LICENCE, src/class.rs, src/colors.rs, src/display.rs, src/enum.rs, src/function.rs, src/interface.rs, src/lib.rs, src/module.rs, src/namespace.rs, src/node.rs, src/params.rs, src/parser.rs, src/printer.rs, src/swc_util.rs, src/tests.rs, src/ts_type.rs, src/ts_type_param.rs, src/type_alias.rs, src/variable.rs
I've updated the year of copyright to 2021
=> chore: update copyright year to 2021

examples/ddoc/main.rs
* This PR adds support for filtering nodes to ddoc:
```shell
$ ./target/debug/examples/ddoc ../deno/std/io/bufio.ts BufReader
```
* This PR is intended to make it easier to test the behavior of [`find_nodes_by_name_recursively`](https://github.com/denoland/deno_doc/blob/45283bcfa0b0c31eb102a13756763145df67d822/src/lib.rs#L42) manually.
=> feat(examples/ddoc): Add support for filtering nodes

.github/workflows/ci.yml, README.md
=> chore: upgrade Rust to 1.51.0

src/interface.rs, src/tests.rs
closes https://github.com/denoland/doc_website/issues/179
=> feat: add string literal support of interface property

.github/workflows/ci.yml, README.md
=> chore: upgrade Rust to 1.53.0

lib/types.d.ts, src/interface.rs, src/tests.rs
=> fix: add method kind to interface methods

lib/types.d.ts
=> fix: correct type def for `TsTypeMappedDef`

.github/workflows/ci.yml
Similar to https://github.com/denoland/deno/pull/14089
=> bump actions/checkout

deno.json
=> chore: ignore lockfile in deno.json

src/html/class.rs, src/html/function.rs, src/html/interface.rs, src/html/jsdoc.rs, src/html/mod.rs, src/html/parameters.rs, src/html/symbol.rs, src/html/symbols/class.rs, src/html/symbols/enum.rs, src/html/symbols/function.rs, src/html/symbols/interface.rs, src/html/symbols/mod.rs, src/html/symbols/namespace.rs, src/html/symbols/type_alias.rs, src/html/symbols/variable.rs, src/html/templates/compound_index.html, src/html/templates/function.html, src/html/templates/index_list.html, src/html/templates/namespace_section.html, src/html/templates/page.html, src/html/templates/search_bar.html, src/html/templates/search_results.html, src/html/types.rs, src/html/util.rs
=> refactor: More rendering using templates

src/html/mod.rs, src/html/symbols/function.rs, src/html/templates/function.html, src/html/templates/html_head.html, src/html/types.rs, src/html/util.rs
=> refactor: Simplify additional CSS

Cargo.lock, Cargo.toml
Updates import_map crate needed for https://github.com/denoland/deno/pull/20410
=> chore: update import_map to 0.17.0

src/diagnostics.rs, src/parser.rs, tests/specs/ModuleDocs.txt, tests/specs/RemoteModuleReExportNoDiagnostics.txt
For https://github.com/denoland/deno/issues/21390
=> fix: don't report diagnostics on remote modules

src/html/mod.rs
=> fix: make find_common_ancestor public

examples/ddoc/main.rs, src/html/jsdoc.rs, src/html/mod.rs, src/html/pages.rs, src/html/sidepanels.rs, src/html/templates/all_symbols.html, src/html/templates/breadcrumbs.html, src/html/templates/html_head.html, src/html/templates/html_tail.html, src/html/templates/index.html, src/html/templates/index_sidepanel.html, src/html/templates/module_doc.html, src/html/templates/page.css, src/html/templates/styles.css, src/html/templates/symbol_page.html, src/html/util.rs, tests/html_test.rs
and some other cleanups and fixes.
=> feat(html): breadcrumbs

Cargo.lock, Cargo.toml
handlebars-rust author here. This patch upgrades handlebars-rust to latest stable release.
=> feat: update handlebars to 5.0

Cargo.lock, Cargo.toml, src/parser.rs, tests/specs/ReexportDeep.txt
For https://github.com/denoland/deno_graph/issues/351
=> fix: better support for deep re-exports

src/html/jsdoc.rs, src/html/templates/module_doc.hbs
Same as denoland/doc_components#93
=> feat(html): deprecated module doc

deno.json, examples/ddoc/main.rs, src/html/jsdoc.rs, src/html/mod.rs, src/html/pages.rs, src/html/render_context.rs, src/html/search.rs, src/html/sidepanels.rs, src/html/symbols/namespace.rs, src/html/templates/doc_entry.hbs, src/html/templates/index_sidepanel.hbs, src/html/templates/namespace_section.hbs, src/html/util.rs, tests/html_test.rs
=> refactor(html): introduce ShortPath struct

src/html/symbols/function.rs, tests/testdata/multiple/b.ts, tests/testdata/symbol_group-syntect.json, tests/testdata/symbol_group-tree-sitter.json, tests/testdata/symbol_group.json
Follow-up to #515.
Closes #481
=> feat(html): display default value of function params

examples/ddoc/main.rs, src/html/mod.rs, src/html/pages.rs, src/html/render_context.rs, src/html/util.rs, src/lib.rs, src/node.rs, src/parser.rs, tests/html_test.rs
=> refactor: use Arc for namespace elements

src/html/mod.rs, src/html/pages.rs, src/html/partition.rs, src/html/render_context.rs, src/html/search.rs, src/html/sidepanels.rs, src/html/symbols/class.rs, src/html/symbols/interface.rs, src/html/symbols/mod.rs, src/html/symbols/namespace.rs, src/html/symbols/type_alias.rs, src/html/symbols/variable.rs, src/html/util.rs
=> feat(html): variable type literal breakdown

src/html/pages.rs, src/html/partition.rs, src/html/render_context.rs, src/html/search.rs, src/html/sidepanels.rs, src/html/symbols/mod.rs, src/html/util.rs, tests/testdata/symbol_search.json
for `deno types`, reduces gen time by about 4 seconds
=> refactor(html): various cleanup and perf improvements

Cargo.lock, Cargo.toml, src/parser.rs, src/ts_type.rs, src/ts_type_param.rs, src/variable.rs, tests/html_test.rs, tests/specs/expando_props/basic.txt, tests/specs/infer_variable.txt, tests/specs_test.rs
Supports documenting properties like:
```ts
export function test() {
}
test.skip = () => {};
```
=> feat: support expando properties

src/diagnostics.rs, tests/specs/private_type_other_module.txt, tests/specs/reexport_deep.txt
This was also causing a panic in the code.
=> fix: private reference diagnostic was displaying incorrect information

src/html/jsdoc.rs
=> fix(html): correct jsdoc link tag handling

src/html/jsdoc.rs
For https://github.com/jsr-io/jsr/issues/571
=> fix(html): render alerts that span multiple child nodes

Cargo.lock, Cargo.toml, src/interface.rs, src/ts_type.rs
Blocked on https://github.com/denoland/deno_ast/pull/260
Blocked on https://github.com/denoland/deno_graph/pull/502
=> fix: Upgrade deno_ast to 0.40.0 and deno_graph 0.80.0

Cargo.toml
Unblocks https://github.com/denoland/deno/pull/26885
=> fix: downgrade url dep
