src/tests.rs
The `doc_test!` macro defines two local variables (`entries` and `doc`),
which are then accessed from the provided `block`.
However, this only compiled due to a bug in rustc: substituted
metavariables cannot refer to names defined within the macro body. For
example, the following ode does not compile:
```rust
macro_rules! foo {
($block:expr) => {
let mut bar = false;
$block
}
}
fn main() {
foo!({bar = true});
}
```
In this case, the `doc_test!` macro was incorrectly allowed to compile
due to the presence of the `#[tokio::test]` macro on the enclosing
function. When the underlying compiler bug is fixed in
https://github.com/rust-lang/rust/pull/75800,
this macro will stop compiling.
I've adjusted the macro to take in a closure instead of a block. This
closure is invoked with the `entries` …
=> Turn block into a closure in test macro

src/class.rs, src/enum.rs, src/function.rs, src/interface.rs, src/namespace.rs, src/node.rs, src/params.rs, src/printer.rs, src/ts_type.rs, src/ts_type_param.rs, src/type_alias.rs, src/variable.rs
When using `deno_doc` as a crate, it is useful to support deserialize, such as deserializing the previously generated JSON data and formatting it through `DocPrinter`
=> refactor: add Deserialize derive to nodes

Cargo.lock, Cargo.toml
`serde_derive` is listed in dependencies, but it is not used at all. Instead we are using `serde::{Serialize, Deserialize}` from `serde` (not `serde_derive`).
So in this PR, I removed `serde_derive` from dependencies.
=> chore: remove serde_derive from dependencies

.github/workflows/ci.yml
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Action and workflow authors who are setting environment variables via stdout should update any usage of the set-env and add-path workflow commands to use the new environment files.
=> Use GITHUB_ENV instead of set-env

src/tests.rs, src/ts_type.rs, src/variable.rs
This PR resolves #33.
This PR implements type inference based on right-hand side value. At the moment, only simple types are inferred:
* `const n = 100`: `n` is inferred to `number`.
* `const d = new Date()`: `d` is inferred to `Date`.
* `const sum = add(1, 2)`: Cannot infer the type of `sum`.
* Add `infer_simple_ts_type_from_var_decl()` to `src/ts_type.rs` and call it from `src/variable.rs` If no type is specified for the variable.
* Refactor `src/ts_type.rs` using factory methods for creating `TsTypeDef`.
**sample.ts**
```typescript
export const hello = "hello, world";
export const i = 100;
export const b = true;
export const re = /hello/
export const bi = 100n;
export const d = new Date();
export const tpl = `foobar`;
```
**Before this fix:**
```
Defined in …
```
=> feat: Infer simple TS types

src/class.rs, src/interface.rs, src/lib.rs, src/tests.rs
This PR implements `detail output for class fields` listed at the issue #4:
**detail output for interface fields:**
```shell
$ ./target/debug/examples/ddoc ../deno/std/encoding/csv.ts ParseOptions.columns
Defined in file:///home/uki00a/ghq/github.com/uki00a/deno/std/encoding/csv.ts:363:2
const columns: string[] | ColumnOptions[]
If you provide `string[]` or `ColumnOptions[]`, those names will be used for header definition.
```
**detail output for class fields:**
```shell
$ ./target/debug/examples/ddoc ../deno/std/io/bufio.ts BufReader.read
Defined in file:///home/uki00a/ghq/github.com/uki00a/deno/std/io/bufio.ts:124:2
async function read(p: Uint8Array): Promise<number | null>
reads data into p.
It returns the number of bytes read into p.
The bytes are taken from at most one Read on the …
```
=> feat: Add support for filtering class and interface fields

src/parser.rs, src/tests.rs
Previously, the `declare` keyword was taken to indicate a global variable and shown in the documentation. However, that is only be the case for ambient declarations - in modules, this just indicates a private value.
Partially fixes #57
=> fix: only include declarations in docs if the file is ambient

examples/ddoc/main.rs, src/class.rs, src/interface.rs, src/node.rs, src/parser.rs, src/tests.rs, src/ts_type.rs, src/ts_type_param.rs
Ref denoland/deno#9617
BREAKING CHANGE: Changes `DocFileLoader`, `parse`, and `parse_with_reexports` APIs
=> fix: Don't use the same syntax for all files

Cargo.lock, Cargo.toml
To fix https://github.com/denoland/deno/issues/10954 and https://github.com/denoland/deno/issues/10893 we need to upgrade swc, so this commit does it so that all the related crates will have the same version.
=> chore: upgrade swc_ecmascript

Cargo.lock, Cargo.toml, src/tests.rs, src/ts_type.rs
This PR deals with TypeScript user-defined type predicate and assertion, which were unimplemented as reported in #102. Additionally, added `pretty_assertions` crate as a dev-dependency so we can easily spot the difference between expected and actual JSON output.
As far as I understand, to address #102 completely, we need to fix [doc_website](https://github.com/denoland/doc_website) as well. I will work on it later.
```ts
export function f1(val1: A | B): val1 is A {}
export function f2(val2: any): asserts val2 is string {}
export function f3(val3: any): asserts val3 {}
export function assertIsDefined<T>(val4: T): asserts val4 is NonNullable<T> {
if (val === undefined || val === null) {
throw new AssertionError(
`Expected 'val' to be defined, but received ${val}`
);
}
}
export class C { …
```
=> feat: handle user-defined type guards

Cargo.lock, Cargo.toml
Need this for an upcomming change to deno based on a breaking change in swc.
=> chore: upgrade swc to 0.46

.github/workflows/ci.yml, README.md, src/class.rs, src/colors.rs, src/function.rs, src/params.rs, src/parser.rs, src/printer.rs, src/ts_type.rs, src/variable.rs
Upgrades Rust to 1.54.0 and applys clippy's fixes.
=> chore: upgrade Rust to 1.54.0

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, examples/ddoc/main.rs, src/lib.rs, src/parser.rs, src/swc_util.rs, src/tests.rs
This integrates `deno_graph` and lays down the prep work for exposing a web assembly API for `deno_graph`.
=> refactor: migrate to deno_graph and other wasm prep-work

lib/types.d.ts, mod.ts
Working with the types, I realised that we need all the types exported, and so instead of re-exporting some from the mod.ts, we should just export them and have them in `lib/types.d.ts` for importing as needed.
=> feat: export all public JS types

.github/workflows/ci.yml, lib/deno_doc.generated.js, src/js_doc.rs
This PR changes the tests to also check for multi-line support where docs are allowed.
Closes #194
=> fix: allow multi-line tag docs

js/test.ts, src/parser.rs, src/tests.rs
Closes https://github.com/denoland/deno_doc/issues/277
=> feat: display non-exported types referenced in exported types

benches/doc_parser.rs, examples/ddoc/main.rs, src/js.rs, src/node.rs, src/parser.rs, src/tests.rs
This is a basic initial implementation.
=> feat: introduce diagnostic for private types referenced by public types

src/interface.rs, src/tests.rs
Didn't realize this problem caim in a pair until after I merged the other one.
=> feat: add missing jsdoc and location to interface's IndexSignature

src/diagnostics.rs, src/swc_util.rs, tests/specs/InternalTag.txt, tests/specs/ModuleDocsIgnoreNoModuleTag.txt
Fixes two issues:
1. `@ignore` tags are respected for the "non-exported" type diagnostics.
2. The `@ignore` tag does not ignore the entire module unless the `@module` tag is also in the jsdoc. I discovered this by accident.
=> fix: better @ignore jsdoc handling

Cargo.lock, Cargo.toml, src/parser.rs, src/util/symbol.rs, src/visibility.rs, tests/specs/PrivateTypeOtherModule.txt, tests/specs/ReExportAll.txt
I recently introduced a bug to deno_doc related to discovering re-exports. We didn't have a test so it wasn't caught.
=> fix: issue discovering re-exports of re-exports

src/function.rs, tests/specs/FunctionAsync.txt
For https://github.com/denoland/deno/issues/21403
=> fix: ignore empty return stmts when determining if return type necessary

src/html/mod.rs, src/html/symbols/namespace.rs, src/html/util.rs
This makes the url resolving as flexible as possible, giving more granular control for generated structures that are different from the default generator
=> refactor: url resolving

src/class.rs, src/decorators.rs, src/enum.rs, src/function.rs, src/interface.rs, src/js_doc.rs, src/node.rs, src/params.rs, src/ts_type.rs, src/ts_type_param.rs, tests/integration_test.rs
Previously wasn't working, because all the nodes marked as `skip_serializing_if` were not also marked as `default`.
=> fix: actually support serde::Deserialize on DocNode

Cargo.lock, Cargo.toml
Looks like cargo formatted the file a little differently. Only updated `deno_graph`
=> chore: update deno_graph 0.67.0

src/html/render_context.rs
This actually used to be like this:
with the difference that I am trying to move away from empty shortpaths.
I wont be adding tests in this PR, but in a follow-up right after (also found a few other issues i'll be addressing there), lets roll this out as quickly as possible
=> fix(html): dont unwrap get file in exports resolver

src/html/templates/namespace_section.hbs
In my package, symbol names were not truncated correctly.
And I fix it.
before:
after(apply changes in devtools):
=> Fix truncate behavior for symbol names in namespace

js/types.d.ts, src/html/jsdoc.rs, src/html/symbols/namespace.rs, src/js_doc.rs, src/printer.rs
Towards #489. Does not include html gen handling.
This also slightly changes the semantics of `@category`, `@example` & `@tags`, as they allowed for an empty doc content, which makes no sense for these tags.
=> feat: `@see` tag

src/html/jsdoc.rs, src/html/mod.rs, src/html/pages.rs, src/html/partition.rs, src/html/render_context.rs, src/html/search.rs, src/html/sidepanels.rs, src/html/symbols/class.rs, src/html/symbols/enum.rs, src/html/symbols/function.rs, src/html/symbols/interface.rs, src/html/symbols/namespace.rs, src/html/symbols/type_alias.rs, src/html/symbols/variable.rs, src/html/types.rs, src/html/usage.rs, src/html/util.rs, tests/testdata/symbol_group-syntect.json, tests/testdata/symbol_group-tree-sitter.json, tests/testdata/symbol_group.json
main change is in src/html/usage.rs
also unifies type of partitioning functions
=> fix(html): don't display destructure import statement in drilldown

deno.json, src/html/jsdoc.rs, tests/snapshots/html_test__html_doc_files_rewrite-16.snap, tests/snapshots/html_test__html_doc_files_rewrite.snap
fixes #565
This PR changes the rendering of 'All symbols' page of local `deno_std/bytes/mod.ts`  like the below (using the command `cargo run --example ddoc ../deno_std/bytes/mod.ts --html --output public`):
BEFORE
AFTER
Also changes the rendering of `@example` tag in API page like the below:
BEFORE
AFTER
=> fix: all symbols summary and example title

examples/ddoc/main.rs, src/html/jsdoc.rs, src/html/render_context.rs, src/html/util.rs, tests/html_test.rs
Follow-up for #586, adding an external linking callback
=> feat(html): external jsdoc module linking

js/allow_leak_test.ts, js/test.ts
This PR separate a test case with sanitizer disabled into a file next to it.
The test cases with sanitizer enabled and disabled can't be mixed because of this issue https://github.com/denoland/deno/issues/22927
Currently the windows CI is flaky because of this issue.
=> test: separate test case which require sanitizer disabled

src/html/symbols/class.rs, src/html/symbols/function.rs, src/html/symbols/namespace.rs, src/html/symbols/type_alias.rs, src/html/symbols/variable.rs, src/html/types.rs, src/html/util.rs
For https://github.com/jsr-io/jsr/issues/724
=> fix(html): proper tag order

js/mod.ts, js/test.ts, lib/lib.rs, src/html/mod.rs, src/html/pages.rs, src/html/render_context.rs, src/html/usage.rs, src/html/util.rs, tests/html_test.rs
and includes a few minor adjustments
=> feat(wasm/html): add callback to generate the default path resolver in resolvePath

src/parser.rs
to unblock JSR. I will investigate this once I am available again
=> fix: add temporary fallbacks for reference resolution

examples/ddoc/main.rs, src/diagnostics.rs, src/html/jsdoc.rs, src/html/mod.rs, src/html/pages.rs, src/html/partition.rs, src/html/search.rs, src/html/symbols/mod.rs, src/html/symbols/namespace.rs, src/html/usage.rs, src/html/util.rs, src/lib.rs, src/node.rs, src/parser.rs, src/printer.rs, src/tests.rs
This doesnt affect JSON output, only the rust API.
This is done in favour of just operating of `DocNodeDef` variants instead of having a special type that mirrors all the variants
Also changes `NamespaceDef` elements to be stored as `Arc` instead of `Rc`.
the html gen still has a `DocNodeKindWithDrilldown` (renamed to `DocNodeKind` in this PR for simplicity), which is mainly used for ordering, which should be moved to ordering on `DocNodeDef` and then also add ordering on `DocNode` since we need that in a few spots.
Additionally its also used for grouping of nodes, but that could be cleaned up to use `DocNodeKindCtx` instead.
However not doing that in this PR.
=> refactor: remove `DocNodeKind`

src/parser.rs, tests/specs/namespace_exports_self.txt
This just ignores self or ancestor exports for the time being.
Closes https://github.com/denoland/deno_doc/pull/599/
=> fix: do not stack overflow when namespace exports itself or an ancestor
